function [E1,E2] = myEigenvalues(q,Omega,delta)
%MYEIGENVALUES
%    [E1,E2] = MYEIGENVALUES(Q,OMEGA,DELTA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Nov-2020 13:29:59

t2 = Omega.^2;
t3 = delta.^2;
t4 = q.^2;
t6 = delta.*q.*8.0;
t5 = t2.*4.0;
t7 = t4.*1.6e+1;
t8 = t3+t5+t6+t7;
t9 = sqrt(t8);
t10 = t9./2.0;
E1 = t4-t10+1.0;
if nargout > 1
    E2 = t4+t10+1.0;
end
